#!/usr/bin/env python3
"""
laying_the_tiling.py -- the 2-D test: lay the Penrose tiling half-tile by half-tile, with no map.

Follows ../laying_the_street/ (1-D: local rules always defect; same-scale copying locks into
repetition; consulting the street's own zoomed-out self lays the quasicrystal).

Tiles are Robinson half-rhombi (two triangle shapes, both handednesses; pairs form the thin and
thick Penrose rhombi). A reference tiling is generated by subdivision from a 10-triangle wheel.
From it we learn only the ATLAS of complete vertex stars (the 2-D analogue of "which letter
patterns are legal") -- checked to be exactly the 8 classic Penrose vertex types.

Growth (always at the frontier edge nearest the centre; a tile is LEGAL if it does not overlap
and every vertex it touches is a contiguous piece of an atlas star, or a complete atlas star):
  LOCAL-DICE    any legal tile at that edge, dice at choices.
  LOCAL-FORCED  first look (nearest 40 edges) for an edge where exactly ONE legal tile fits;
                else dice at the nearest edge. (The smarter local strategy.)
  COPY          same-scale likeness: find an already-laid INTERIOR edge whose owning half-tile
                matches (shape, handedness, which edge) and whose vertex stars extend ours;
                copy the half-tile across it (most recently laid twin first).
  SCALE         the laid patch consults its own zoomed-out self: S(P) = mirror(tau^2 *
                subdivide^2(P)) -- verified exact self-similarity of the reference about its centre.
                The next tile is the tile S(P) places across the edge (if legal).
  WRONGSCALE    the same with one subdivision (tau^1, no mirror): not the tiling's own symmetry.
A run JAMS when the chosen edge has no legal tile (LOCAL) or the rule proposes none / an illegal
one (COPY, SCALE, WRONGSCALE). Measured: jams and tiles laid before them; for SCALE from the
centre also exact agreement with the reference; SCALE from off-centre seeds.
asserts + nonzero exit.
"""
from __future__ import annotations
import os, sys, math, cmath, random, collections, json

HERE = os.path.dirname(os.path.abspath(__file__))
REPORT = os.path.join(HERE, "results", "laying_tiling_report.txt")
DATA = os.path.join(HERE, "results", "laying_tiling.json")
LINES, FAILS = [], []
TAU = (1 + 5 ** 0.5) / 2
LEVEL = 8
MAX_TILES = 500
RUNS = 30
SEED = 20260925


def log(s=""):
    LINES.append(s); print(s, flush=True)


def require(cond, msg):
    LINES.append(("  [PASS] " if cond else "  [FAIL] ") + msg)
    print(("  [PASS] " if cond else "  [FAIL] ") + msg, flush=True)
    if not cond:
        FAILS.append(msg)


# ------------------------------------------------------------------ tiles and substitution
def subdivide(tris):
    out = []
    for c, A, B, C in tris:
        if c == 0:
            P = A + (B - A) / TAU
            out += [(0, C, P, B), (1, P, C, A)]
        else:
            Q = B + (A - B) / TAU; R = B + (C - B) / TAU
            out += [(1, R, C, A), (1, Q, R, B), (0, R, Q, A)]
    return out


def wheel():
    t = []
    for i in range(10):
        B = cmath.rect(1, (2 * i - 1) * math.pi / 10); C = cmath.rect(1, (2 * i + 1) * math.pi / 10)
        if i % 2 == 0:
            B, C = C, B
        t.append((0, 0j, B, C))
    return t


def key(z):
    return (round(z.real, 6), round(z.imag, 6))


def orient(A, B, C):
    return (B - A).real * (C - A).imag - (B - A).imag * (C - A).real


def corners(tris):
    V = collections.defaultdict(list)
    for c, A, B, C in tris:
        pts = {"A": A, "B": B, "C": C}; o = orient(A, B, C) > 0
        for nm, other in (("A", "BC"), ("B", "CA"), ("C", "AB")):
            v = pts[nm]; p, q = pts[other[0]], pts[other[1]]
            a1 = math.atan2((p - v).imag, (p - v).real); a2 = math.atan2((q - v).imag, (q - v).real)
            d = (a2 - a1) % (2 * math.pi)
            if d > math.pi:
                a1, a2, d = a2, a1, 2 * math.pi - d
            V[key(v)].append((a1 % (2 * math.pi), d, (c, nm, o)))
    return V


def star(lst):
    lst = sorted(lst); labs = tuple(l for _, _, l in lst)
    return min(labs[i:] + labs[:i] for i in range(len(labs)))


def canon(t):
    return (t[0], frozenset(key(z) for z in t[1:]))


def inside(p, A, B, C):
    d1, d2, d3 = orient(A, B, p), orient(B, C, p), orient(C, A, p)
    if min(abs(d1), abs(d2), abs(d3)) < 1e-12:
        return False
    return (d1 > 0) == (d2 > 0) == (d3 > 0)


REF = wheel()
for _ in range(LEVEL):
    REF = subdivide(REF)
SCALE_LEN = abs(REF[0][1] - REF[0][2])
_V = corners(REF)
STARS = {star(l) for k, l in _V.items() if abs(complex(*k)) < 0.6
         and abs(sum(d for _, d, _ in l) - 2 * math.pi) < 1e-6}
ARCS = set()
for s in STARS:
    n = len(s)
    for i in range(n):
        for L in range(1, n + 1):
            ARCS.add(tuple(s[(i + j) % n] for j in range(L)))
TEMPL = {}
for _t in REF:
    TEMPL.setdefault((_t[0], orient(*_t[1:]) > 0), _t)


class Patch:
    def __init__(s, tris):
        s.tris = []; s.edges = collections.defaultdict(list); s.V = collections.defaultdict(list)
        for t in tris:
            s.add(t)

    def add(s, t):
        s.tris.append(t)
        c, A, B, C = t
        for p, q in ((A, B), (B, C), (C, A)):
            s.edges[frozenset((key(p), key(q)))].append(t)
        for k, l in corners([t]).items():
            s.V[k] += l

    def frontier(s):
        out = []
        for ek, ts in s.edges.items():
            if len(ts) == 1:
                t = ts[0]
                pts = [z for z in t[1:] if key(z) in ek]; r = [z for z in t[1:] if key(z) not in ek][0]
                out.append((pts[0], pts[1], r, t))
        out.sort(key=lambda e: (abs((e[0] + e[1]) / 2), key((e[0] + e[1]) / 2)))
        return out

    def vertex_ok(s, k, extra):
        lst = sorted(s.V[k] + extra); n = len(lst)
        tot = sum(d for _, d, _ in lst)
        if tot > 2 * math.pi + 1e-6:
            return False
        if abs(tot - 2 * math.pi) < 1e-6:
            return star(lst) in STARS
        wrap = lambda x: (x + math.pi) % (2 * math.pi) - math.pi
        start = next((i for i in range(n)
                      if abs(wrap(lst[i - 1][0] + lst[i - 1][1] - lst[i][0])) > 1e-6), None)
        if start is None:
            return False
        seq = lst[start:] + lst[:start]; arcs = [[seq[0]]]
        for i in range(1, n):
            pa, pd, _ = seq[i - 1]; a = seq[i][0]
            g = wrap(a - (pa + pd))
            if abs(g) < 1e-6:
                arcs[-1].append(seq[i])
            elif g < 0:
                return False                                     # overlapping corners
            else:
                arcs.append([seq[i]])
        return all(tuple(l for _, _, l in arc) in ARCS for arc in arcs)

    def legal(s, t):
        cen = sum(t[1:]) / 3
        for u in s.tris:
            if abs(u[1] - cen) < 3 * SCALE_LEN and (inside(cen, *u[1:]) or any(inside(z, *u[1:]) for z in t[1:])):
                return False
        if canon(t) in {canon(u) for u in s.edges.get(frozenset((key(t[1]), key(t[2]))), [])}:
            return False
        return all(s.vertex_ok(k, v) for k, v in corners([t]).items())

    def candidates(s, p, q, r):
        out = {}
        for (c, o), (tc, A, B, C) in TEMPL.items():
            P = {"A": A, "B": B, "C": C}
            for X, Y, Z in (("A", "B", "C"), ("B", "C", "A"), ("C", "A", "B"),
                            ("B", "A", "C"), ("C", "B", "A"), ("A", "C", "B")):
                x, y, z = P[X], P[Y], P[Z]
                if abs(abs(y - x) - abs(q - p)) > 1e-6:
                    continue
                a = (q - p) / (y - x)
                zz = p + a * (z - x)
                if orient(p, q, zz) * orient(p, q, r) >= 0:
                    continue
                img = {X: p, Y: q, Z: zz}
                nt = (tc, img["A"], img["B"], img["C"])
                if s.legal(nt):
                    out[canon(nt)] = nt
        return list(out.values())


def seed_patch(center, radius):
    return [t for t in REF if max(abs(z - center) for z in t[1:]) < radius]


def zoom(tris, steps, mirror):
    S = list(tris)
    for _ in range(steps):
        S = subdivide(S)
    f = TAU ** steps
    return [(c, (A.conjugate() if mirror else A) * f, (B.conjugate() if mirror else B) * f,
             (C.conjugate() if mirror else C) * f) for c, A, B, C in S]


def lay(rule, seed, rng, center=0j):
    P = Patch(seed); n0 = len(P.tris); P.guesses = 0
    S_index = None
    while len(P.tris) - n0 < MAX_TILES:
        fr = P.frontier()
        if not fr:
            return len(P.tris) - n0, "closed", P
        p, q, r, own = fr[0]
        if rule == "LOCAL-DICE":
            cs = P.candidates(p, q, r)
            if not cs:
                return len(P.tris) - n0, "JAM", P
            P.add(rng.choice(sorted(cs, key=lambda t: canon(t)[0])))
        elif rule == "LOCAL-FORCED":
            chosen, first = None, None
            for e in fr[:40]:
                cs = P.candidates(*e[:3])
                if not cs:
                    return len(P.tris) - n0, "JAM", P
                if len(cs) == 1:
                    chosen = cs[0]; break
                if first is None:
                    first = cs
            if chosen is None:
                P.guesses += 1
            P.add(chosen if chosen else rng.choice(first))
        elif rule in ("SCALE", "WRONGSCALE"):
            steps, mir = (2, True) if rule == "SCALE" else (1, False)
            ek = frozenset((key(p), key(q)))
            prop = None
            for attempt in range(2):
                if S_index is None or attempt == 1:
                    S = zoom([(c, A - center, B - center, C - center) for c, A, B, C in P.tris], steps, mir)
                    S = [(c, A + center, B + center, C + center) for c, A, B, C in S]
                    S_index = collections.defaultdict(list)
                    for t in S:
                        for a_, b_ in ((t[1], t[2]), (t[2], t[3]), (t[3], t[1])):
                            S_index[frozenset((key(a_), key(b_)))].append(t)
                opts = [t for t in S_index.get(ek, [])
                        if orient(p, q, [z for z in t[1:] if key(z) not in ek][0]) * orient(p, q, r) < 0]
                if opts:
                    prop = opts[0]; break
            if prop is None:
                return len(P.tris) - n0, "NOTHING", P
            if not P.legal(prop):
                return len(P.tris) - n0, "ILLEGAL", P
            P.add(prop)
        elif rule == "COPY":
            role = None
            for X, Y in (("A", "B"), ("B", "C"), ("C", "A")):
                pts = {"A": own[1], "B": own[2], "C": own[3]}
                if {key(pts[X]), key(pts[Y])} == {key(p), key(q)}:
                    role = (X, Y) if key(pts[X]) == key(p) else (Y, X)
            sig = (own[0], orient(*own[1:]) > 0, role)
            prop = None
            for t in reversed(P.tris[:-1]):
                if (t[0], orient(*t[1:]) > 0) != sig[:2]:
                    continue
                pts = {"A": t[1], "B": t[2], "C": t[3]}
                p2, q2 = pts[role[0]], pts[role[1]]
                ek2 = frozenset((key(p2), key(q2)))
                if len(P.edges[ek2]) != 2:
                    continue
                other = [u for u in P.edges[ek2] if u is not t][0]
                a = (q - p) / (q2 - p2)
                nt = (other[0],) + tuple(p + a * (z - p2) for z in other[1:])
                if orient(p, q, [z for z in nt[1:] if key(z) not in {key(p), key(q)}][0]) * orient(p, q, r) < 0:
                    prop = nt; break
            if prop is None:
                return len(P.tris) - n0, "NOTHING", P
            if not P.legal(prop):
                return len(P.tris) - n0, "ILLEGAL", P
            P.add(prop)
    return len(P.tris) - n0, "ok", P


def main():
    log("=" * 90)
    log("LAYING THE TILING -- Penrose laid half-tile by half-tile, with no map")
    log("=" * 90)
    log(f"  reference: {len(REF)} half-tiles (level {LEVEL}); atlas of complete vertex stars: {len(STARS)}")
    require(len(STARS) == 8, "the learned atlas is exactly the 8 classic Penrose vertex types")
    seed = seed_patch(0j, 3 * SCALE_LEN)
    rest = sorted([t for t in REF if t not in seed and max(abs(z) for z in t[1:]) < 25 * SCALE_LEN],
                  key=lambda t: abs(sum(t[1:]) / 3))
    Pv = Patch(seed); bad = 0
    for t in rest:
        bad += not Pv.legal(t); Pv.add(t)
    require(bad == 0, f"the legality test never rejects a genuine Penrose tile ({len(rest)} tiles "
                      f"re-laid in order, 0 rejected)")
    out = {}

    # ---- LOCAL arms ----
    log("-" * 90)
    for rule in ("LOCAL-DICE", "LOCAL-FORCED"):
        rs = [lay(rule, seed, random.Random(SEED + k)) for k in range(RUNS)]
        jams = [n for n, st, _ in rs if st == "JAM"]
        refset = {canon(t) for t in REF}
        agree = [sum(1 for t in P.tris if canon(t) in refset) / len(P.tris) for _, _, P in rs]
        guesses = [P.guesses for _, _, P in rs]
        out[rule] = dict(jams=len(jams), sizes=[n for n, _, _ in rs], status=[st for _, st, _ in rs],
                         agree=agree, guesses=guesses)
        log(f"  {rule:<13} agreement with the true tiling: min {min(agree):.1%}, all-exact "
            f"{sum(1 for x in agree if x == 1.0)}/{RUNS}; guesses per run (no forced edge within "
            f"40): median {sorted(guesses)[RUNS // 2]}, max {max(guesses)}")
        log(f"  {rule:<13} {RUNS} runs: jammed {len(jams)}/{RUNS}; tiles before the jam: "
            f"median {sorted(jams)[len(jams) // 2] if jams else '-'} (range "
            f"{min(jams) if jams else '-'}-{max(jams) if jams else '-'}); reached {MAX_TILES}: "
            f"{sum(1 for _, st, _ in rs if st == 'ok')}")
    require(out["LOCAL-DICE"]["jams"] > 0,
            "LOCAL-DICE jams: growing by local fitting alone reaches edges where nothing fits")
    lf = out["LOCAL-FORCED"]
    log(f"  NOTE (not predicted): LOCAL-FORCED never jammed ({lf['jams']}/{RUNS}); in 2-D a smarter LOCAL "
        f"strategy can avoid jams (cf. Onoda-Steinhardt-DiVincenzo-Socolar 1988 on forced growth)")

    # ---- COPY, SCALE, WRONGSCALE from the centre ----
    log("-" * 90)
    for rule in ("COPY", "SCALE", "WRONGSCALE"):
        n, st, P = lay(rule, seed, random.Random(SEED))
        match = None
        if rule == "SCALE":
            refset = {canon(t) for t in REF}
            match = sum(1 for t in P.tris if canon(t) in refset) / len(P.tris)
        out[rule] = dict(n=n, status=st, match=match)
        log(f"  {rule:<10} from the centre: laid {n} half-tiles, ended: {st}"
            f"{'' if match is None else '; agrees with the reference on %.1f%% of tiles' % (100 * match)}")
    require(out["SCALE"]["status"] == "ok" and out["SCALE"]["match"] == 1.0,
            f"SCALE (the patch consults its own zoomed-out self) lays {MAX_TILES} half-tiles with no "
            f"jam, every one exactly the Penrose tile")
    require(out["WRONGSCALE"]["status"] != "ok",
            f"WRONGSCALE (one zoom step: not the tiling's own symmetry) fails "
            f"({out['WRONGSCALE']['status']} after {out['WRONGSCALE']['n']})")
    log(f"  COPY (same-scale twin) from the centre: {out['COPY']['status']} after {out['COPY']['n']}")

    # ---- SCALE from off-centre seeds (the 2-D 'misaligned start') ----
    log("-" * 90)
    rng = random.Random(SEED + 99)
    verts = [complex(*k) for k in _V if 6 * SCALE_LEN < abs(complex(*k)) < 12 * SCALE_LEN]
    offs = []
    for v in rng.sample(verts, 12):
        sd = seed_patch(v, 3 * SCALE_LEN)
        n, st, _ = lay("SCALE", [(c, A - v, B - v, C - v) for c, A, B, C in sd], None)
        offs.append((n, st))
    log(f"  SCALE from 12 off-centre seeds (a legal Penrose patch around a vertex that is NOT the "
        f"inflation centre): {offs}")
    out["SCALE_offcentre"] = offs
    require(all(st != "ok" for _, st in offs),
            "SCALE from an off-centre seed breaks down: the zoomed-out self only predicts correctly "
            "from a patch that is truly self-similar about the growth centre")

    os.makedirs(os.path.join(HERE, "results"), exist_ok=True)
    json.dump(out, open(DATA, "w"))
    log("=" * 90)
    if FAILS:
        log(f"FAILED: {len(FAILS)} check(s): " + "; ".join(FAILS))
    else:
        log("ALL CHECKS PASSED.")
    open(REPORT, "w").write("\n".join(LINES) + "\n")
    sys.exit(1 if FAILS else 0)


if __name__ == "__main__":
    main()
