#!/usr/bin/env python3
"""
Address-channel degradation under phason disorder: Ammann-Beenker vs Penrose.

Both substrates are generated by cut-and-project at matched scale, perturbed by
independent jitter of each candidate's perpendicular coordinate before the
acceptance test, and scored the same way: can a model recover the privileged-site
label from perpendicular-space coordinates alone?

A shuffle null (perpendicular coordinates permuted across vertices) runs beside
every measurement. Results are means over several disorder seeds.
"""

import argparse
import sys

import numpy as np
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import StratifiedKFold
from sklearn.neighbors import KDTree

sys.path.insert(0, __file__.rsplit("/", 1)[0])
import generate_ab as GA
import generate_penrose as GP
from audit_with_nulls import adjacency, shared_core_labels
from multiplex_ab import substrate_disordered as ab_disordered

AB_OFFSET = np.array([0.1381, 0.0927])
PEN_OFFSET = np.array([0.1237, 0.0891])


def penrose_disordered(amplitude, extent, seed):
    lifts, par, perp = GP.generate(extent, PEN_OFFSET, disorder=amplitude, seed=seed)
    return lifts, par, perp, GP.build_edges(lifts)


def labels_for(par, edges, interior=0.75):
    n = len(par)
    rad = np.linalg.norm(par - par.mean(0), axis=1)
    active = np.sort(np.argsort(rad)[:int(round(interior * n))]).tolist()
    med = float(np.median(np.linalg.norm(par[[u for u, _ in edges]]
                                         - par[[v for _, v in edges]], axis=1)))
    q = KDTree(par).query_radius(par[active], r=3.0 * med)
    seeds = {active[k]: q[k].tolist() for k in range(len(active))}
    y, _, _, _ = shared_core_labels(adjacency(n, edges), active, seeds)
    return active, y


def auc(X, y, seed=0):
    y = np.asarray(y, int)
    if y.sum() < 8 or (1 - y).sum() < 8:
        return float("nan")
    cv = StratifiedKFold(3, shuffle=True, random_state=seed)
    p = np.zeros(len(y))
    for tr, te in cv.split(X, y):
        m = HistGradientBoostingClassifier(max_iter=200, random_state=0)
        m.fit(X[tr], y[tr])
        p[te] = m.predict_proba(X[te])[:, 1]
    return float(roc_auc_score(y, p))


def address_matrix(lifts, perp, name):
    cols = [perp, np.linalg.norm(perp, axis=1)[:, None]]
    if name == "Penrose":                     # Z^5 needs the third coordinate
        cols.append(lifts.sum(1)[:, None].astype(float))
    return np.column_stack(cols)


def run(name, maker, extent, amps, seeds):
    print(f"\n{name}")
    print(f"{'disorder':>9} {'vertices':>9} {'positives':>10} "
          f"{'address AUC':>18} {'shuffle null':>14}")
    rows = {}
    for a in amps:
        aucs, shufs, nv, npos = [], [], [], []
        for s in seeds:
            lifts, par, perp, E = maker(a, extent, s)
            active, y = labels_for(par, E)
            X = address_matrix(lifts, perp, name)[active]
            rng = np.random.default_rng(1000 + s)
            Xs = address_matrix(lifts, perp, name)[rng.permutation(len(perp))][active]
            v, w = auc(X, y, s), auc(Xs, y, s)
            if not np.isnan(v):
                aucs.append(v); shufs.append(w); nv.append(len(par)); npos.append(int(y.sum()))
        if not aucs:
            print(f"{a:9.2f} {'-':>9} {'too few positives':>10}")
            continue
        m = float(np.mean(aucs))
        sd = float(np.std(aucs, ddof=1)) if len(aucs) > 1 else 0.0
        print(f"{a:9.2f} {int(np.mean(nv)):9d} {int(np.mean(npos)):10d} "
              f"{m:11.4f} +- {sd:.4f} {np.mean(shufs):14.4f}")
        rows[a] = (m, sd, int(np.mean(npos)))
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seeds", type=int, default=5)
    ap.add_argument("--ab-extent", type=int, default=18)
    ap.add_argument("--pen-extent", type=int, default=14)
    args = ap.parse_args()

    amps = [0.0, 0.05, 0.10, 0.20, 0.30, 0.40]
    seeds = list(range(args.seeds))

    print("=" * 72)
    print("Address channel vs phason disorder, matched scale, "
          f"{args.seeds} seeds per point")
    print("=" * 72)

    ab = run("Ammann-Beenker", lambda a, e, s: ab_disordered(a, e, s), args.ab_extent, amps, seeds)
    pen = run("Penrose", lambda a, e, s: penrose_disordered(a, e, s), args.pen_extent, amps, seeds)

    print("\n" + "=" * 72)
    print(f"{'disorder':>9} {'AB':>18} {'Penrose':>18} {'gap':>9}")
    for a in amps:
        if a not in ab or a not in pen:
            have = "AB only" if a in ab else ("Penrose only" if a in pen else "neither")
            print(f"{a:9.2f} {'':>18} {'':>18}   (skipped: {have})")
            continue
        (m1, s1, _), (m2, s2, _) = ab[a], pen[a]
        print(f"{a:9.2f} {m1:11.4f} +- {s1:.4f} {m2:11.4f} +- {s2:.4f} {m1-m2:+9.4f}")


if __name__ == "__main__":
    main()
