#!/usr/bin/env python3
"""
Hard validation: the rank-4 congruence construction must reproduce Penrose exactly.

`generate_penrose.py` builds Penrose P3 as a Z^5 cut-and-project, accepting a
lattice point when its index sum j = sum(n_k) lies in {1,2,3,4} and its
perpendicular projection falls in the corresponding pentagon. It is verified
against the published substrate.

The claim under test is that this was never five-dimensional. The kernel of
Z^5 -> Z[zeta_5] is generated by (1,1,1,1,1), whose index sum is 5, so:

    a_k = n_k - n_4                        rank-4 coordinates, k = 0..3
    sum(a) = j - 5 n_4  ==  j  (mod 5)     index sum is a congruence class
    n @ PERP = a @ PERP[:4]                since sum(PERP) = 0

giving a purely rank-4 acceptance test with a two-dimensional address:

    accept a  iff  c = sum(a) mod 5 in {1,2,3,4}  and  perp(a) in window[c]

and a star of five directions e_0, e_1, e_2, e_3, -(1,1,1,1) - the fifth being
the image of the Z^5 step e_4, since raising n_4 by one lowers every a_k by one.

Pass condition: the two planar point sets agree exactly inside a radius both
patches fully cover, and the edge sets agree there too.
"""

import argparse
import sys

import numpy as np

sys.path.insert(0, __file__.rsplit("/", 1)[0])
import generate_penrose as GP

STAR4 = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1],
                  [-1, -1, -1, -1]], dtype=np.int64)


def penrose_rank4(extent, offset):
    """Penrose P3 as a rank-4 cut and project with a congruence-classed window."""
    win = GP.windows()
    perp4 = GP.PERP[:4]
    par4 = GP.PAR[:4]
    axis = np.arange(-extent, extent + 1, dtype=np.int64)
    grid = np.array(np.meshgrid(*([axis] * 4), indexing="ij")).reshape(4, -1).T
    c = grid.sum(1) % 5
    keep = np.zeros(len(grid), dtype=bool)
    pp = grid @ perp4 + offset
    for j in range(1, 5):
        m = c == j
        if m.any():
            keep[m] = GP.inside(win[j], pp[m])
    a = grid[keep]
    return a, a @ par4, a @ perp4 + offset


def edges_rank4(a):
    idx = {tuple(r): i for i, r in enumerate(a)}
    E = set()
    for i, row in enumerate(a):
        for s in STAR4:
            j = idx.get(tuple(row + s))
            if j is not None:
                E.add((min(i, j), max(i, j)))
    return E


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--extent", type=int, default=12)
    ap.add_argument("--radius", type=float, default=0.0)
    args = ap.parse_args()
    offset = np.array([0.1237, 0.0891])

    n5, par5, _ = GP.generate(args.extent, offset)
    a5 = n5[:, :4] - n5[:, 4:5]                     # Z^5 -> rank 4
    print(f"Z^5 Penrose      : {len(n5)} vertices, index sums "
          f"{sorted(set(n5.sum(1).tolist()))}")
    print(f"mapped to rank 4 : |a|_inf max = {np.abs(a5).max()}")

    ext4 = int(np.abs(a5).max())
    a4, par4, _ = penrose_rank4(ext4, offset)
    print(f"rank-4 Penrose   : {len(a4)} vertices at extent {ext4}")

    # Compare inside a radius both patches cover completely.
    R = args.radius or 0.55 * min(np.abs(par5).max(), np.abs(par4).max())
    s5 = {tuple(r) for r in a5[np.linalg.norm(par5, axis=1) <= R]}
    s4 = {tuple(r) for r in a4[np.linalg.norm(par4, axis=1) <= R]}
    print(f"\ncomparison radius: {R:.3f}")
    print(f"  Z^5   -> rank 4 : {len(s5)} points")
    print(f"  rank-4 direct   : {len(s4)} points")
    print(f"  only in Z^5     : {len(s5 - s4)}")
    print(f"  only in rank-4  : {len(s4 - s5)}")

    # Edge sets, expressed as unordered pairs of rank-4 coordinates.
    def edge_pairs(a, par, R):
        keep = np.linalg.norm(par, axis=1) <= R
        sub = a[keep]
        idx = {tuple(r): i for i, r in enumerate(sub)}
        out = set()
        for row in sub:
            for s in STAR4:
                if tuple(row + s) in idx:
                    out.add((tuple(row), tuple(row + s)))
        return out

    e5 = edge_pairs(a5, par5, R)
    e4 = edge_pairs(a4, par4, R)
    print(f"  edges in Z^5    : {len(e5)}")
    print(f"  edges in rank-4 : {len(e4)}")
    print(f"  edge difference : {len(e5 ^ e4)}")

    ok = not (s5 ^ s4) and not (e5 ^ e4)
    print("\n" + ("PASS - rank-4 congruence construction reproduces Penrose exactly"
                  if ok else "*** FAIL ***"))
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
