#!/usr/bin/env python3
"""
Reverse-Loop Test -- substrate geometry (cut-and-project machinery).

NOTE ON PROVENANCE
------------------
The reverse-loop protocol instructs the implementer to *reuse* the linger
experiment's walker machinery, hull/depth computation and address-residue
metric "unchanged". That pipeline is NOT present in this repository (the repo
contains the papers plus the `silent_corruption` audit, which operates on
externally supplied CSV substrates that are likewise not committed). Per the
protocol's own fallback ("keep the code's convention and flag the difference in
the findings memo"), the machinery here is reconstructed to the conventions the
repository *does* document:

  * substrates generated by de Bruijn / cut-and-project multigrids
    (Ammann-Beenker: Z^4 multigrid, octagonal acceptance window; Penrose: Z^5
    pentagrid, pentagonal residue-class windows);
  * "address" = perpendicular-space coordinates; the silent_corruption code
    uses (perp_x, perp_y, perp_r, k_sum_mod5);
  * "depth" = distance from the acceptance-window boundary in perp space.

Everything reconstructed here is flagged in FINDINGS.md.

Construction
------------
We use the standard cut-and-project method. Lift lattice is Z^N. Two orthogonal
2-planes of R^N are the parallel (physical) space and the perpendicular
(internal / address) space, each spanned by a "star" of N unit vectors:

    xi_par[j]  = (cos(2*pi*j/N),   sin(2*pi*j/N))
    xi_perp[j] = (cos(2*pi*m*j/N), sin(2*pi*m*j/N))     (winding m)

  N=4, m=3  -> Ammann-Beenker (8-fold; opposite grid lines identified -> 4 dirs)
  N=5, m=2  -> Penrose (5-fold)

A lift K in Z^N is a tiling vertex iff its perpendicular image lies inside the
acceptance window W (the projection of the unit hypercube [0,1]^N into perp
space -- a zonotope: an octagon for N=4, a decagon for N=5). Physical position
is the parallel image. Two vertices are graph-neighbours iff their lifts differ
by exactly one unit vector +-e_j (a rhombus edge).

Depth of a vertex = signed distance from its perp image to the boundary of W
(positive inside, 0 on the boundary). Deep = near the window centre.
"""

import numpy as np


# --------------------------------------------------------------------------- #
# Substrate definitions
# --------------------------------------------------------------------------- #

# par_step / perp_step are the angular increments (radians) between successive
# grid-line families in parallel and perpendicular space.
#   Ammann-Beenker: 4 grids at 45deg (pi/4); perp winding x3.
#   Penrose:        5 grids at 72deg (2pi/5); perp winding x2.
#
# gamma_sum is the de Bruijn "cut" offset sum Sum_j gamma_j (the individual
# offsets stay generic; only their sum is pinned here). It is *not* a free knob:
#   * Penrose (pentagrid): a faithful P3 rhombus tiling requires Sum gamma_j in Z.
#     Integer sum -> exactly four residue classes {1,2,3,4} (the four-pentagon
#     occupation domain) and maximum vertex coordination 7. A non-integer sum
#     yields a *generalized* Penrose tiling with a spurious 5th residue class (0)
#     and coordination up to 10 -- not real Penrose. We pin it to 0.
#   * Ammann-Beenker (4-grid): its octagonal tiling (max coordination 8) is
#     unaffected by the sum; 0.5 (maximally generic) is kept as-is. Do not touch.
SUBSTRATES = {
    "ammann_beenker": dict(N=4, par_step=np.pi / 4,   perp_step=3 * np.pi / 4,
                           gamma_sum=0.5),
    "penrose":        dict(N=5, par_step=2 * np.pi / 5, perp_step=4 * np.pi / 5,
                           gamma_sum=0.0),
}


def star_vectors(N, par_step, perp_step):
    """Parallel and perpendicular star vectors, shape (N, 2)."""
    j = np.arange(N)
    par = np.stack([np.cos(par_step * j), np.sin(par_step * j)], axis=1)
    perp = np.stack([np.cos(perp_step * j), np.sin(perp_step * j)], axis=1)
    return par, perp


def _convex_polygon(points):
    """Convex hull of a 2D point cloud, returned CCW as (V,2) vertices."""
    pts = np.unique(np.round(points, 9), axis=0)
    # Andrew's monotone chain
    pts = pts[np.lexsort((pts[:, 1], pts[:, 0]))]

    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])

    lower = []
    for p in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)
    upper = []
    for p in pts[::-1]:
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)
    hull = np.array(lower[:-1] + upper[:-1])
    return hull


def polygon_halfplanes(hull):
    """Convex polygon (CCW) -> (outward_normals (E,2), offsets (E,)) so that a
    point p is inside iff normals @ p <= offsets, and signed boundary distance
    = min(offsets - normals @ p) (positive inside)."""
    center = hull.mean(axis=0)
    normals, offsets = [], []
    V = len(hull)
    for i in range(V):
        a, b = hull[i], hull[(i + 1) % V]
        edge = b - a
        n = np.array([edge[1], -edge[0]], dtype=float)
        nn = np.linalg.norm(n)
        if nn == 0:
            continue
        n /= nn
        if n @ (a - center) < 0:
            n = -n
        normals.append(n)
        offsets.append(n @ a)
    return np.array(normals), np.array(offsets), center


def window_depth(perp_pts, normals, offsets):
    """Signed distance to window boundary (positive inside). Vectorized."""
    h = perp_pts @ normals.T  # (P, E)
    return (offsets[None, :] - h).min(axis=1)


# --------------------------------------------------------------------------- #
# Patch generation
# --------------------------------------------------------------------------- #

class Patch:
    """A finite cut-and-project patch with vertex graph, perp coords, depth."""

    def __init__(self, substrate, radius=9.0, gammas=None,
                 n_zones=4, gamma_sum=None, verbose=False):
        cfg = SUBSTRATES[substrate]
        self.substrate = substrate
        self.N = cfg["N"]
        self.radius = radius
        self.par_star, self.perp_star = star_vectors(
            self.N, cfg["par_step"], cfg["perp_step"])
        # grid-line offsets (the "cut"). Individual offsets are generic (distinct,
        # no >2-line concurrence); their SUM is pinned by the substrate's
        # gamma_sum (see SUBSTRATES): integer for a faithful Penrose P3, 0.5 for
        # AB. `gamma_sum` overrides the default (e.g. gamma_sum=0.5 reproduces the
        # legacy generalized-Penrose substrate for diffing); logged in summary.
        if gammas is None:
            target = cfg["gamma_sum"] if gamma_sum is None else gamma_sum
            base = np.array([0.2, 0.13, 0.37, 0.06, 0.29])[: self.N]
            base = base - base.sum() / self.N + (target / self.N)  # generic
            gammas = base
        self.gammas = np.asarray(gammas, dtype=float)
        self._build_multigrid(radius, verbose)
        self._assign_zones(n_zones)

    # -- de Bruijn multigrid intersection method ----------------------------- #
    def _build_multigrid(self, radius, verbose):
        """Every intersection of two grid lines is a tiling vertex. Vertex lift
        K_l = ceil(z . n_l + gamma_l); physical = K @ par_star, perp = K @
        perp_star. Vertices deduplicated by lift."""
        N = self.N
        n_par = self.par_star  # grid normals coincide with parallel star
        # index range for grid lines to cover the patch radius (+margin)
        # physical position of a vertex is (N/2) times the parallel image of its
        # lift, so a grid-line crossing at |z| corresponds to a vertex at
        # ~ (N/2)|z|. Sweep z out far enough to cover the requested radius.
        zmax = 2.0 * radius / N + 3.0
        krange = int(np.ceil(zmax)) + 3
        verts = {}
        eye = np.eye(N, dtype=np.int64)
        for a in range(N):
            for b in range(a + 1, N):
                na, nb = n_par[a], n_par[b]
                det = na[0] * nb[1] - na[1] * nb[0]
                if abs(det) < 1e-9:
                    continue
                for ka in range(-krange, krange + 1):
                    ca = ka - self.gammas[a]
                    for kb in range(-krange, krange + 1):
                        cb = kb - self.gammas[b]
                        # solve na.z = ca, nb.z = cb
                        zx = (ca * nb[1] - cb * na[1]) / det
                        zy = (na[0] * cb - nb[0] * ca) / det
                        if zx * zx + zy * zy > zmax * zmax:
                            continue
                        z = np.array([zx, zy])
                        K0 = np.ceil(n_par @ z + self.gammas - 1e-9).astype(np.int64)
                        K0[a], K0[b] = ka, kb
                        # the four corners of the rhombus meeting at this crossing
                        for da in (0, 1):
                            for db in (0, 1):
                                K = K0 + da * eye[a] + db * eye[b]
                                verts[tuple(K.tolist())] = None
        K = np.array(sorted(verts.keys()), dtype=np.int64)
        par = K @ self.par_star
        r = np.linalg.norm(par, axis=1)
        keep = r <= radius
        K, par = K[keep], par[keep]
        perp = K @ self.perp_star
        self.K = K
        self.par = par
        self.perp = perp
        self.n = len(K)
        self.residue_class = (K.sum(axis=1) % N).astype(np.int64)
        self._index = {tuple(k): i for i, k in enumerate(K.tolist())}
        self._build_edges()
        self._compute_depth()
        if verbose:
            print(f"[{self.substrate}] vertices={self.n} edges={len(self.edges)} "
                  f"depth in [{self.depth.min():.3f},{self.depth.max():.3f}]")

    def _compute_depth(self):
        """Depth = distance to acceptance-window boundary. The window (occupation
        domain) is recovered empirically as the convex hull of realized perp
        coordinates -- per residue class for Penrose (pentagonal windows), single
        hull for AB (octagonal window)."""
        depth = np.zeros(self.n)
        if self.substrate == "penrose":
            groups = [np.where(self.residue_class == r)[0]
                      for r in range(self.N)]
        else:
            groups = [np.arange(self.n)]
        self.windows = {}
        for g in groups:
            if len(g) < 3:
                depth[g] = 0.0
                continue
            hull = _convex_polygon(self.perp[g])
            if len(hull) < 3:
                depth[g] = 0.0
                continue
            normals, offsets, _ = polygon_halfplanes(hull)
            depth[g] = np.clip(window_depth(self.perp[g], normals, offsets),
                               0, None)
            if len(g):
                self.windows[int(self.residue_class[g[0]])] = hull
        self.depth = depth

    def _build_edges(self):
        N = self.N
        adj = [[] for _ in range(self.n)]
        edges = set()
        eye = np.eye(N, dtype=np.int64)
        for i, k in enumerate(self.K.tolist()):
            for j in range(N):
                for s in (+1, -1):
                    nb = tuple((np.array(k) + s * eye[j]).tolist())
                    q = self._index.get(nb)
                    if q is not None and q > i:
                        edges.add((i, q))
                        adj[i].append(q)
                        adj[q].append(i)
        self.edges = sorted(edges)
        self.adj = [np.array(sorted(a), dtype=np.int64) for a in adj]

    # -- depth zones --------------------------------------------------------- #
    def _assign_zones(self, n_zones):
        """Partition vertices into n_zones by depth quantile. Zone 0 = shallow
        (near boundary), zone n_zones-1 = deep (near window centre)."""
        self.n_zones = n_zones
        qs = np.quantile(self.depth, np.linspace(0, 1, n_zones + 1))
        qs[0] -= 1e-9
        qs[-1] += 1e-9
        self.zone_edges = qs
        self.zone = np.clip(np.digitize(self.depth, qs) - 1, 0, n_zones - 1)

    # -- convenience --------------------------------------------------------- #
    def largest_component(self):
        """Return vertex indices of the largest connected component."""
        seen = np.full(self.n, -1, dtype=np.int64)
        best = []
        comp_id = 0
        for s in range(self.n):
            if seen[s] >= 0:
                continue
            stack = [s]
            seen[s] = comp_id
            comp = []
            while stack:
                u = stack.pop()
                comp.append(u)
                for v in self.adj[u]:
                    if seen[v] < 0:
                        seen[v] = comp_id
                        stack.append(v)
            if len(comp) > len(best):
                best = comp
            comp_id += 1
        return np.array(sorted(best), dtype=np.int64)

    def address(self, i):
        """Address (perp) coordinate of vertex i."""
        return self.perp[i]


if __name__ == "__main__":
    for name in SUBSTRATES:
        p = Patch(name, radius=9.0, verbose=True)
        comp = p.largest_component()
        degs = np.array([len(a) for a in p.adj])
        print(f"    largest component: {len(comp)}/{p.n}  "
              f"mean degree {degs.mean():.2f}  "
              f"zone sizes {np.bincount(p.zone, minlength=p.n_zones).tolist()}")
